@extends('layouts.main')
@section('title','Hospedaje | El Mirador')
@section('content')
    @include('layouts.partials.herosection')
    @include('layouts.partials.aboutsection')
    @include('layouts.partials.servicessection')
    @include('layouts.partials.roomsection')
    @include('layouts.partials.testimonialsection')
    @include('layouts.partials.blogsection')
@endsection